--*================================================================*
--* DB2 DDL - Driver License Issuance System (DLIS)
--* Member  : DLIS0002-CREATE-INDEXES
--* Desc    : Create all indexes for performance
--*================================================================*

-- CANDIDATE
CREATE UNIQUE INDEX DLIS.XCAND01
    ON DLIS.CANDIDATE (CANDIDATE_ID);

CREATE UNIQUE INDEX DLIS.XCAND02
    ON DLIS.CANDIDATE (ID_NUMBER);

CREATE INDEX DLIS.XCAND03
    ON DLIS.CANDIDATE (LAST_NAME, FIRST_NAME);

-- LICENSE_APPLICATION
CREATE UNIQUE INDEX DLIS.XAPPL01
    ON DLIS.LICENSE_APPLICATION (APPLICATION_ID);

CREATE INDEX DLIS.XAPPL02
    ON DLIS.LICENSE_APPLICATION (CANDIDATE_ID, LICENSE_TYPE, APPLICATION_STATUS);

CREATE INDEX DLIS.XAPPL03
    ON DLIS.LICENSE_APPLICATION (APPLICATION_STATUS);

-- DRIVING_HISTORY
CREATE UNIQUE INDEX DLIS.XHIST01
    ON DLIS.DRIVING_HISTORY (HISTORY_ID);

CREATE INDEX DLIS.XHIST02
    ON DLIS.DRIVING_HISTORY (CANDIDATE_ID, RECORD_STATUS);

CREATE INDEX DLIS.XHIST03
    ON DLIS.DRIVING_HISTORY (CANDIDATE_ID, INCIDENT_TYPE, RECORD_STATUS);

-- PAYMENT
CREATE UNIQUE INDEX DLIS.XPAY01
    ON DLIS.PAYMENT (PAYMENT_ID);

CREATE INDEX DLIS.XPAY02
    ON DLIS.PAYMENT (APPLICATION_ID);

CREATE UNIQUE INDEX DLIS.XPAY03
    ON DLIS.PAYMENT (RECEIPT_NUMBER);

-- ISSUED_LICENSE
CREATE UNIQUE INDEX DLIS.XLIC01
    ON DLIS.ISSUED_LICENSE (LICENSE_ID);

CREATE UNIQUE INDEX DLIS.XLIC02
    ON DLIS.ISSUED_LICENSE (LICENSE_NUMBER);

CREATE INDEX DLIS.XLIC03
    ON DLIS.ISSUED_LICENSE (CANDIDATE_ID, LICENSE_TYPE, LICENSE_STATUS);

CREATE INDEX DLIS.XLIC04
    ON DLIS.ISSUED_LICENSE (APPLICATION_ID);

-- AUTHORITY_USER
CREATE UNIQUE INDEX DLIS.XAUTH01
    ON DLIS.AUTHORITY_USER (AUTHORITY_USER_ID);

CREATE UNIQUE INDEX DLIS.XAUTH02
    ON DLIS.AUTHORITY_USER (USER_CODE);

CREATE INDEX DLIS.XAUTH03
    ON DLIS.AUTHORITY_USER (AUTHORITY_LEVEL, ACTIVE_STATUS);

-- LICENSE_FEE_SCHEDULE
CREATE UNIQUE INDEX DLIS.XFEE01
    ON DLIS.LICENSE_FEE_SCHEDULE (FEE_SCHEDULE_ID);

CREATE INDEX DLIS.XFEE02
    ON DLIS.LICENSE_FEE_SCHEDULE
    (LICENSE_TYPE, FEE_TYPE, ACTIVE_STATUS, EFFECTIVE_DATE);
