--*================================================================*
--* DB2 DDL - Driver License Issuance System (DLIS)
--* Member  : DLIS0003-GRANTS
--* Desc    : Grant privileges to application IDs
--*================================================================*

-- Grant to application batch ID
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.CANDIDATE
    TO DLISAPPL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.LICENSE_APPLICATION
    TO DLISAPPL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.DRIVING_HISTORY
    TO DLISAPPL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.PAYMENT
    TO DLISAPPL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.ISSUED_LICENSE
    TO DLISAPPL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.AUTHORITY_USER
    TO DLISAPPL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.LICENSE_FEE_SCHEDULE
    TO DLISAPPL;

-- Grant to CICS region user ID
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.CANDIDATE          TO DLISCICS;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.LICENSE_APPLICATION TO DLISCICS;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.DRIVING_HISTORY    TO DLISCICS;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.PAYMENT            TO DLISCICS;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.ISSUED_LICENSE     TO DLISCICS;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.AUTHORITY_USER     TO DLISCICS;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE DLIS.LICENSE_FEE_SCHEDULE TO DLISCICS;
