-- ============================================================
-- DLIS DB2 DDL — Indexes
-- ============================================================

-- CANDIDATE indexes
CREATE INDEX DLIS.IDX_CAND_IDNUM   ON DLIS.CANDIDATE     (ID_NUMBER);
CREATE INDEX DLIS.IDX_CAND_NAME    ON DLIS.CANDIDATE     (LAST_NAME, FIRST_NAME);
CREATE INDEX DLIS.IDX_CAND_STATUS  ON DLIS.CANDIDATE     (RECORD_STATUS);

-- LICENSE_APPLICATION indexes
CREATE INDEX DLIS.IDX_APP_CAND     ON DLIS.LICENSE_APPLICATION (CANDIDATE_ID);
CREATE INDEX DLIS.IDX_APP_STATUS   ON DLIS.LICENSE_APPLICATION (APPLICATION_STATUS);
CREATE INDEX DLIS.IDX_APP_TYPE     ON DLIS.LICENSE_APPLICATION (CANDIDATE_ID, LICENSE_TYPE, APPLICATION_STATUS);

-- DRIVING_HISTORY indexes
CREATE INDEX DLIS.IDX_HIST_CAND    ON DLIS.DRIVING_HISTORY (CANDIDATE_ID, RECORD_STATUS);
CREATE INDEX DLIS.IDX_HIST_TYPE    ON DLIS.DRIVING_HISTORY (INCIDENT_TYPE, SUSPENSION_END_DATE);

-- ISSUED_LICENSE indexes
CREATE INDEX DLIS.IDX_ISSLOC_CAND  ON DLIS.ISSUED_LICENSE  (CANDIDATE_ID, LICENSE_STATUS);
CREATE INDEX DLIS.IDX_ISSLOC_TYPE  ON DLIS.ISSUED_LICENSE  (CANDIDATE_ID, LICENSE_TYPE, LICENSE_STATUS);
CREATE INDEX DLIS.IDX_ISSLOC_NUM   ON DLIS.ISSUED_LICENSE  (LICENSE_NUMBER);

-- PAYMENT indexes
CREATE INDEX DLIS.IDX_PAY_APP      ON DLIS.PAYMENT          (APPLICATION_ID);
CREATE INDEX DLIS.IDX_PAY_CAND     ON DLIS.PAYMENT          (CANDIDATE_ID);

-- LICENSE_FEE_SCHEDULE indexes
CREATE INDEX DLIS.IDX_FEE_LOOKUP   ON DLIS.LICENSE_FEE_SCHEDULE
    (LICENSE_TYPE, FEE_TYPE, ACTIVE_STATUS, EFFECTIVE_DATE, EXPIRY_DATE);

-- AUTHORITY_USER indexes
CREATE INDEX DLIS.IDX_AUTH_CODE    ON DLIS.AUTHORITY_USER   (USER_CODE);
CREATE INDEX DLIS.IDX_AUTH_LEVEL   ON DLIS.AUTHORITY_USER   (AUTHORITY_LEVEL, ACTIVE_STATUS);
