      *================================================================*
      * DB2 DDL: DLIS Schema
      * Tables converted from CA Gen encyclopedia entities
      *
      * Target: IBM Db2 for z/OS
      * Schema: DLIS
      *
      * Tables:
      *   CANDIDATE            ← CANDIDATE.ENT
      *   LICENSE_APPLICATION  ← LICENSE-APPLICATION.ENT
      *   DRIVING_HISTORY      ← DRIVING-HISTORY.ENT
      *   PAYMENT              ← PAYMENT.ENT
      *   ISSUED_LICENSE       ← ISSUED-LICENSE.ENT
      *   AUTHORITY_USER       ← AUTHORITY-USER.ENT
      *   LICENSE_FEE_SCHEDULE ← LICENSE-FEE-SCHEDULE.ENT
      *================================================================*

-- =============================================================
-- Table: DLIS.CANDIDATE
-- CA Gen Entity: CANDIDATE.ENT
-- =============================================================
CREATE TABLE DLIS.CANDIDATE (
    CANDIDATE_ID         BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME           VARCHAR(30)     NOT NULL,
    LAST_NAME            VARCHAR(30)     NOT NULL,
    DATE_OF_BIRTH        DATE            NOT NULL,
    ID_NUMBER            VARCHAR(20)     NOT NULL,
    ADDRESS_LINE_1       VARCHAR(50)     NOT NULL,
    ADDRESS_LINE_2       VARCHAR(50),
    CITY                 VARCHAR(30)     NOT NULL,
    STATE_PROVINCE       VARCHAR(30)     NOT NULL,
    POSTAL_CODE          VARCHAR(10),
    COUNTRY              VARCHAR(30)     NOT NULL,
    PHONE_NUMBER         VARCHAR(15),
    EMAIL_ADDRESS        VARCHAR(60),
    CREATED_DATE         DATE            NOT NULL DEFAULT CURRENT DATE,
    RECORD_STATUS        CHAR(1)         NOT NULL DEFAULT 'A',
    CONSTRAINT PK_CANDIDATE        PRIMARY KEY (CANDIDATE_ID),
    CONSTRAINT UQ_CANDIDATE_ID_NUM UNIQUE      (ID_NUMBER),
    CONSTRAINT CHK_CANDIDATE_STATUS CHECK (RECORD_STATUS IN ('A','I'))
);

CREATE INDEX IDX_CANDIDATE_ID_NUM
    ON DLIS.CANDIDATE (ID_NUMBER);

-- =============================================================
-- Table: DLIS.LICENSE_APPLICATION
-- CA Gen Entity: LICENSE-APPLICATION.ENT
-- =============================================================
CREATE TABLE DLIS.LICENSE_APPLICATION (
    APPLICATION_ID           BIGINT      NOT NULL GENERATED ALWAYS AS IDENTITY,
    CANDIDATE_ID             BIGINT      NOT NULL,
    LICENSE_TYPE             CHAR(1)     NOT NULL,
    APPLICATION_DATE         DATE        NOT NULL DEFAULT CURRENT DATE,
    APPLICATION_STATUS       CHAR(2)     NOT NULL DEFAULT 'PE',
    ELIGIBILITY_CHECK_STATUS CHAR(1)     DEFAULT 'U',
    ELIGIBILITY_CHECK_DATE   DATE,
    ELIGIBILITY_CHECK_NOTES  VARCHAR(200),
    HISTORY_CHECK_STATUS     CHAR(1)     DEFAULT 'U',
    HISTORY_CHECK_DATE       DATE,
    HISTORY_CHECK_NOTES      VARCHAR(200),
    PAYMENT_STATUS           CHAR(1)     DEFAULT 'U',
    PAYMENT_REFERENCE        VARCHAR(20),
    APPROVAL_1_STATUS        CHAR(1)     DEFAULT 'U',
    APPROVAL_1_AUTHORITY     VARCHAR(50),
    APPROVAL_1_DATE          DATE,
    APPROVAL_1_NOTES         VARCHAR(200),
    APPROVAL_2_STATUS        CHAR(1)     DEFAULT 'U',
    APPROVAL_2_AUTHORITY     VARCHAR(50),
    APPROVAL_2_DATE          DATE,
    APPROVAL_2_NOTES         VARCHAR(200),
    REJECTION_REASON         VARCHAR(300),
    CREATED_DATE             DATE        NOT NULL DEFAULT CURRENT DATE,
    LAST_UPDATED_DATE        DATE        NOT NULL DEFAULT CURRENT DATE,
    CREATED_BY               VARCHAR(20) NOT NULL,
    LAST_UPDATED_BY          VARCHAR(20) NOT NULL,
    CONSTRAINT PK_LICENSE_APPLICATION PRIMARY KEY (APPLICATION_ID),
    CONSTRAINT FK_LA_CANDIDATE
        FOREIGN KEY (CANDIDATE_ID) REFERENCES DLIS.CANDIDATE (CANDIDATE_ID),
    CONSTRAINT CHK_LICENSE_TYPE      CHECK (LICENSE_TYPE IN ('L','P','O')),
    CONSTRAINT CHK_APP_STATUS        CHECK (APPLICATION_STATUS IN ('PE','EC','HC','PA','A2','AP','IS','RE')),
    CONSTRAINT CHK_ELIG_STATUS       CHECK (ELIGIBILITY_CHECK_STATUS IN ('P','F','U')),
    CONSTRAINT CHK_HIST_STATUS       CHECK (HISTORY_CHECK_STATUS IN ('P','F','U')),
    CONSTRAINT CHK_PAY_STATUS        CHECK (PAYMENT_STATUS IN ('P','U','W')),
    CONSTRAINT CHK_APP1_STATUS       CHECK (APPROVAL_1_STATUS IN ('A','R','U')),
    CONSTRAINT CHK_APP2_STATUS       CHECK (APPROVAL_2_STATUS IN ('A','R','U'))
);

CREATE INDEX IDX_LA_CANDIDATE
    ON DLIS.LICENSE_APPLICATION (CANDIDATE_ID, LICENSE_TYPE, APPLICATION_STATUS);

-- =============================================================
-- Table: DLIS.DRIVING_HISTORY
-- CA Gen Entity: DRIVING-HISTORY.ENT
-- =============================================================
CREATE TABLE DLIS.DRIVING_HISTORY (
    HISTORY_ID               BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    CANDIDATE_ID             BIGINT          NOT NULL,
    INCIDENT_DATE            DATE            NOT NULL,
    INCIDENT_TYPE            CHAR(2)         NOT NULL,
    INCIDENT_DESCRIPTION     VARCHAR(300),
    DEMERIT_POINTS           SMALLINT        DEFAULT 0,
    FINE_AMOUNT              DECIMAL(10,2)   DEFAULT 0,
    FINE_PAID_STATUS         CHAR(1),
    SUSPENSION_START_DATE    DATE,
    SUSPENSION_END_DATE      DATE,
    COURT_CASE_NUMBER        VARCHAR(20),
    RECORDED_BY_AUTHORITY    VARCHAR(50),
    RECORD_STATUS            CHAR(1)         NOT NULL DEFAULT 'A',
    CONSTRAINT PK_DRIVING_HISTORY     PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_DH_CANDIDATE
        FOREIGN KEY (CANDIDATE_ID) REFERENCES DLIS.CANDIDATE (CANDIDATE_ID),
    CONSTRAINT CHK_INCIDENT_TYPE      CHECK (INCIDENT_TYPE IN ('OF','AC','SU','DQ')),
    CONSTRAINT CHK_DH_RECORD_STATUS   CHECK (RECORD_STATUS IN ('A','I')),
    CONSTRAINT CHK_FINE_PAID          CHECK (FINE_PAID_STATUS IN ('Y','N') OR FINE_PAID_STATUS IS NULL),
    CONSTRAINT CHK_DEMERIT_POSITIVE   CHECK (DEMERIT_POINTS >= 0),
    CONSTRAINT CHK_FINE_POSITIVE      CHECK (FINE_AMOUNT >= 0)
);

CREATE INDEX IDX_DH_CANDIDATE
    ON DLIS.DRIVING_HISTORY (CANDIDATE_ID, RECORD_STATUS);

-- =============================================================
-- Table: DLIS.PAYMENT
-- CA Gen Entity: PAYMENT.ENT
-- =============================================================
CREATE TABLE DLIS.PAYMENT (
    PAYMENT_ID               BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    APPLICATION_ID           BIGINT          NOT NULL,
    CANDIDATE_ID             BIGINT          NOT NULL,
    PAYMENT_DATE             DATE            NOT NULL DEFAULT CURRENT DATE,
    PAYMENT_AMOUNT           DECIMAL(10,2)   NOT NULL,
    PAYMENT_METHOD           CHAR(2)         NOT NULL,
    PAYMENT_REFERENCE        VARCHAR(30)     NOT NULL,
    PAYMENT_STATUS           CHAR(1)         NOT NULL DEFAULT 'P',
    LICENSE_TYPE             CHAR(1)         NOT NULL,
    FEE_TYPE                 CHAR(2)         NOT NULL,
    RECEIPT_NUMBER           VARCHAR(20),
    PROCESSED_BY             VARCHAR(20),
    NOTES                    VARCHAR(200),
    CONSTRAINT PK_PAYMENT             PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT FK_PAY_APPLICATION
        FOREIGN KEY (APPLICATION_ID) REFERENCES DLIS.LICENSE_APPLICATION (APPLICATION_ID),
    CONSTRAINT FK_PAY_CANDIDATE
        FOREIGN KEY (CANDIDATE_ID) REFERENCES DLIS.CANDIDATE (CANDIDATE_ID),
    CONSTRAINT CHK_PAY_METHOD         CHECK (PAYMENT_METHOD IN ('CC','DC','EF','CS','CH')),
    CONSTRAINT CHK_PAY_STATUS         CHECK (PAYMENT_STATUS IN ('S','F','R','P')),
    CONSTRAINT CHK_PAY_FEE_TYPE       CHECK (FEE_TYPE IN ('IF','RF','LF','PF')),
    CONSTRAINT CHK_PAY_AMOUNT_POS     CHECK (PAYMENT_AMOUNT > 0)
);

-- =============================================================
-- Table: DLIS.ISSUED_LICENSE
-- CA Gen Entity: ISSUED-LICENSE.ENT
-- =============================================================
CREATE TABLE DLIS.ISSUED_LICENSE (
    LICENSE_ID               BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    APPLICATION_ID           BIGINT          NOT NULL,
    CANDIDATE_ID             BIGINT          NOT NULL,
    LICENSE_NUMBER           VARCHAR(20)     NOT NULL,
    LICENSE_TYPE             CHAR(1)         NOT NULL,
    ISSUE_DATE               DATE            NOT NULL,
    EXPIRY_DATE              DATE            NOT NULL,
    LICENSE_STATUS           CHAR(1)         NOT NULL DEFAULT 'A',
    VEHICLE_CLASS            CHAR(2)         NOT NULL,
    RESTRICTIONS             VARCHAR(200),
    DEMERIT_BALANCE          SMALLINT        DEFAULT 12,
    ISSUED_BY_AUTHORITY      VARCHAR(50)     NOT NULL,
    ISSUED_BY_OFFICER        VARCHAR(50)     NOT NULL,
    RENEWAL_COUNT            SMALLINT        DEFAULT 0,
    PREVIOUS_LICENSE_ID      BIGINT,
    NOTES                    VARCHAR(300),
    CONSTRAINT PK_ISSUED_LICENSE      PRIMARY KEY (LICENSE_ID),
    CONSTRAINT UQ_LICENSE_NUMBER      UNIQUE (LICENSE_NUMBER),
    CONSTRAINT FK_IL_APPLICATION
        FOREIGN KEY (APPLICATION_ID) REFERENCES DLIS.LICENSE_APPLICATION (APPLICATION_ID),
    CONSTRAINT FK_IL_CANDIDATE
        FOREIGN KEY (CANDIDATE_ID) REFERENCES DLIS.CANDIDATE (CANDIDATE_ID),
    CONSTRAINT CHK_IL_LICENSE_TYPE    CHECK (LICENSE_TYPE IN ('L','P','O')),
    CONSTRAINT CHK_IL_STATUS          CHECK (LICENSE_STATUS IN ('A','S','E','C','R')),
    CONSTRAINT CHK_VEHICLE_CLASS      CHECK (VEHICLE_CLASS IN ('A','B','C','D')),
    CONSTRAINT CHK_EXPIRY_AFTER_ISSUE CHECK (EXPIRY_DATE > ISSUE_DATE)
);

CREATE INDEX IDX_IL_CANDIDATE
    ON DLIS.ISSUED_LICENSE (CANDIDATE_ID, LICENSE_TYPE, LICENSE_STATUS);

-- =============================================================
-- Table: DLIS.AUTHORITY_USER
-- CA Gen Entity: AUTHORITY-USER.ENT
-- =============================================================
CREATE TABLE DLIS.AUTHORITY_USER (
    AUTHORITY_USER_ID        BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    USER_CODE                VARCHAR(20)     NOT NULL,
    USER_NAME                VARCHAR(60)     NOT NULL,
    AUTHORITY_NAME           VARCHAR(50)     NOT NULL,
    AUTHORITY_LEVEL          CHAR(1)         NOT NULL,
    DEPARTMENT               VARCHAR(50),
    PHONE_NUMBER             VARCHAR(15),
    EMAIL_ADDRESS            VARCHAR(60),
    ACTIVE_STATUS            CHAR(1)         NOT NULL DEFAULT 'A',
    LICENSE_TYPES_AUTHORISED VARCHAR(3),
    CONSTRAINT PK_AUTHORITY_USER      PRIMARY KEY (AUTHORITY_USER_ID),
    CONSTRAINT UQ_USER_CODE           UNIQUE (USER_CODE),
    CONSTRAINT CHK_AUTHORITY_LEVEL    CHECK (AUTHORITY_LEVEL IN ('1','2')),
    CONSTRAINT CHK_AU_ACTIVE_STATUS   CHECK (ACTIVE_STATUS IN ('A','I'))
);

-- =============================================================
-- Table: DLIS.LICENSE_FEE_SCHEDULE
-- CA Gen Entity: LICENSE-FEE-SCHEDULE.ENT
-- =============================================================
CREATE TABLE DLIS.LICENSE_FEE_SCHEDULE (
    FEE_SCHEDULE_ID          BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    LICENSE_TYPE             CHAR(1)         NOT NULL,
    FEE_TYPE                 CHAR(2)         NOT NULL,
    FEE_AMOUNT               DECIMAL(10,2)   NOT NULL,
    EFFECTIVE_DATE           DATE            NOT NULL,
    EXPIRY_DATE              DATE,
    CURRENCY_CODE            CHAR(3)         NOT NULL,
    DESCRIPTION              VARCHAR(200),
    ACTIVE_STATUS            CHAR(1)         NOT NULL DEFAULT 'A',
    CONSTRAINT PK_FEE_SCHEDULE        PRIMARY KEY (FEE_SCHEDULE_ID),
    CONSTRAINT CHK_FS_LICENSE_TYPE    CHECK (LICENSE_TYPE IN ('L','P','O')),
    CONSTRAINT CHK_FS_FEE_TYPE        CHECK (FEE_TYPE IN ('IF','RF','LF','PF')),
    CONSTRAINT CHK_FS_ACTIVE_STATUS   CHECK (ACTIVE_STATUS IN ('A','I')),
    CONSTRAINT CHK_FS_FEE_AMOUNT_POS  CHECK (FEE_AMOUNT > 0)
);

CREATE INDEX IDX_FS_LOOKUP
    ON DLIS.LICENSE_FEE_SCHEDULE (LICENSE_TYPE, FEE_TYPE, ACTIVE_STATUS, EFFECTIVE_DATE);
